/*
 * The one way to reach a committed asset.
 *
 * `asset-index.json` is regenerated by `npm run assets`, and because it is a
 * literal the compiler knows every slug in it. `media['wall/tile-99']` is a type
 * error, not a runtime `undefined` handed to `next/image` - which matters here
 * because a missing asset would otherwise surface as a hole in the layout rather
 * than as a failure.
 *
 * Every entry carries its intrinsic size. Nothing on this page may render
 * without width and height: the Template Wall alone is 48 tiles, and a grid that
 * reflows as they load would spend the whole CLS budget (PRD section 8) on its
 * first screen.
 */

import assetIndex from './asset-index.json'
import type { MediaAsset, MediaImage, MediaVideo } from './types.ts'

export type { MediaAsset, MediaImage, MediaVideo }

/**
 * Every committed asset, by slug. Slugs read `group/name`; see
 * `scripts/assets/manifest.ts` for what each group covers.
 *
 * The `satisfies` is what makes the generated file part of the type system: a
 * pipeline that emitted an entry without a `width`, or a poster without a `src`,
 * fails `npm run typecheck` instead of reaching a component.
 */
export const media = assetIndex.assets satisfies Record<string, MediaAsset>

export type MediaSlug = keyof typeof media

/** True for the thirteen clips, which are the only entries carrying a poster. */
export function isVideo(asset: MediaAsset): asset is MediaVideo {
  return 'poster' in asset
}
