/*
 * The one way to reach a committed asset.
 *
 * `asset-index.json` is regenerated by `npm run assets`, and because it is a
 * literal the compiler knows every slug in it. `media['wall/tile-99']` is a type
 * error, not a runtime `undefined` handed to `next/image` - which matters here
 * because a missing asset would otherwise surface as a hole in the layout rather
 * than as a failure.
 *
 * Every entry carries its intrinsic size. Nothing on this page may render
 * without width and height: the Template Wall alone is 48 tiles, and a grid that
 * reflows as they load would spend the whole CLS budget (PRD section 8) on its
 * first screen.
 */

import assetIndex from './asset-index.json'

/** A still: an image, or the poster frame standing in for a clip. */
export type MediaImage = {
  readonly src: string
  readonly width: number
  readonly height: number
}

export type MediaVideo = MediaImage & {
  /** Every clip has one. `preload="none"` means this is what a visitor sees. */
  readonly poster: MediaImage
}

/**
 * Every committed asset, by slug. Slugs read `group/name`; see
 * `scripts/assets/manifest.ts` for what each group covers.
 */
export const media = assetIndex.assets

export type MediaSlug = keyof typeof media

/** True for the thirteen clips, which are the only entries carrying a poster. */
export function isVideo(asset: MediaImage | MediaVideo): asset is MediaVideo {
  return 'poster' in asset
}
